export const GIG_LIST_REQUEST = "GIG_LIST_REQUEST";
export const GIG_LIST_SUCCESS = "GIG_LIST_SUCCESS";
export const GIG_LIST_FAIL = "GIG_LIST_FAIL";

export const USER_GIG_LIST_REQUEST = "USER_GIG_LIST_REQUEST";
export const USER_GIG_LIST_SUCCESS = "USER_GIG_LIST_SUCCESS";
export const USER_GIG_LIST_FAIL = "USER_GIG_LIST_FAIL";

export const CREATE_GIG_LIST_REQUEST = "CREATE_GIG_LIST_REQUEST";
export const CREATE_GIG_LIST_SUCCESS = "CREATE_GIG_LIST_SUCCESS";
export const CREATE_GIG_LIST_FAIL = "CREATE_GIG_LIST_FAIL";

export const INSERT_GIG_LIST_REQUEST = "INSERT_GIG_LIST_REQUEST";
export const INSERT_GIG_LIST_SUCCESS = "INSERT_GIG_LIST_SUCCESS";
export const INSERT_GIG_LIST_FAIL = "INSERT_GIG_LIST_FAIL";
